### PR TITLE
Update to 7.0

### PR DESCRIPTION
**Pull request by Kongledyret**

### CODE REVIEW

**Comment by aymanrb** [comment]
Thank you for the contribution.

I would prefer of we keep this optional though or have have a new command for it for those who need it. In my case for instance I still have legacy apps that doesn't work well with PHP7

**Review by aymanrb — APPROVED** [review]

**Comment by Kongledyret** [comment]
Sure thing. Maybe add a option to install the ppa for php5? Since its removed from 16.04 and above if not added.

**Comment by aymanrb** [comment]
Yep, let's keep this the default then and I will add a new option in the menu for the poor guys like me who can't go with 7 that installs 5.6 for them.

**Comment by Kongledyret** [comment]
Sounds great ;) Cheers for this script though!

**Pull request merged**
